
services:
  backend:
    build: ./backend

    ports:
      - "5000:5005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./backend:/server


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app

