describe('Add Contact', () => {
    it('Should be able to add new contact', () => {
        cy.visit("http://localhost:3000/admin/addContact")
        cy.get('[data-cy="add-contact"]').should('exist')
            .should('have.text', "Add New Contact")
        cy.get('[data-cy="contact-headline"]').should('exist')
            .should('have.text', "Contact Name")
        cy.get('[data-cy="email-headline"]').should('exist')
            .should('have.text', "Email")
        cy.get('[data-cy="company-headline"]').should('exist')
            .should('have.text', "Company")
        cy.get('[data-cy="position-headline"]').should('exist')
            .should('have.text', "Position")
        cy.get('[data-cy="phone-headline"]').should('exist')
            .should('have.text', "Phone Number")
        cy.get('[data-cy="contact_name"]').should('exist')
        cy.get('[data-cy="email"]').should('exist')
        cy.get('[data-cy="company"]').should('exist')
        cy.get('[data-cy="position"]').should('exist')
        cy.get('[data-cy="phone"]').should('exist')
    })
    it('Placeholders should contain a type', () => {
        cy.visit("http://localhost:3000/admin/addContact")
        cy.get('[data-cx="input-contact"]').type("Mia Mitsumori")
        cy.get('[data-cx="input-email"]').type("mia@gmail.com")
        cy.get('[data-cx="input-company"]').type("Mia Enterprises")
        cy.get('[data-cx="input-position"]').type("Toddler")
        cy.get('[data-cx="input-phone"]').type("(612-212-4423)")
        cy.get('[data-cy="cancel"]').click()
        cy.url().should('contain', '/admin/contacttable')
    })
})