describe(`add project screen`, () => {
    it("should test all the placeholders and headline", () => {
        cy.visit("http://localhost:3000/admin/addProject")
        cy.get('[data-cy="add-title"]').should('exist')
            .should('have.text', "Add New Project")
        cy.get('[data-cy="project-headline"]').should('exist')
            .should('have.text', "Project Name")
        cy.get('[data-cy="address-headline"]').should('exist')
            .should('have.text', "Address")
        cy.get('[data-cy="city_headline"]').should('exist')
            .should('have.text', "City, State")
        cy.get('[data-cy="scope_headline"]').should('exist')
            .should('have.text', "Scope of Work")
        cy.get('[data-cy="company_headline"]').should('exist')
            .should('have.text', "Company")
        cy.get('[data-cy="contact_headline"]').should('exist')
            .should('have.text', "Contact")
        cy.get('[data-cy="job_headline"]').should('exist')
            .should('have.text', "Job Number")
        cy.get('[data-cy="description_headline"]').should('exist')
            .should('have.text', "Description")
        cy.get('[data-cy="project_name"]').should('exist')
        cy.get('[data-cy="address"]').should('exist')
        cy.get('[data-cy="city"]').should('exist')
        cy.get('[data-cy="scope_of_work"]').should('exist')
        cy.get('[data-cy="company"]').should('exist')
        cy.get('[data-cy="contact"]').should('exist')
        cy.get('[data-cy="job_number"]').should('exist')
        cy.get('[data-cy="description"]').should('exist')

    })
    it("placeholders should contain a type", () => {
        cy.visit('http://localhost:3000/admin/addProject')
        cy.get('[data-cx="input-project"]').type("Chattnooga Water Treatment Plant")
        cy.get('[data-cx="input-address"]').type("1290 Water Way")
        cy.get('[data-cx="input_city"]').type("Chattanooga, TN")
        cy.get('[data-cx="input_scope"]').type("1220009")
        cy.get('[data-cx="input_company"]').type("Morgan Stanley")
        cy.get('[data-cx="input_contact"]').type("Kim Smith")
        cy.get('[data-cx="input_job_number"]').type("123456")
        cy.get('[data-cx="input_description"]').type("Description Example")

    })
})